### PR TITLE
Dump Illuminate\Mail\Mailable

### PR DESCRIPTION
**Pull request by AnandPilania**
# 🛻 LaraDumps Pull Request

<br/><table><tr><td>❗ You <b>MUST</b> use this template to submit a Pull Request or it will NOT be accepted. ❗</td></tr></table><br/>

Welcome and thank you for your interest in contributing to our project.

## Guidelines

`   🗒️ `  Please read the [Contributing Guide](https://github.com/laradumps/laradumps/blob/main/CONTRIBUTING.md) and follow all steps listed there.

`   ✍️ `  Give this PR a meaningful title.

`   📣 `  Describe your PR details below.

## Pull Request Information
Add `mailable`: sends Mailable as table and preview.

### Motivation

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

### Related Issue(s)

This PR Fixes the Issue #_____.

### Description

This Pull Request will log/dump Illuminate\Mail\Mailable.

```
ds()->mailable(new \App\Mail\TestMail(), $preview = true||false)
```

By default, `preview` is `false`;

`mailable` method returns `LaraDumps` instance, so can be chained with other available methods

```
ds()->mailable(...)->toScreen(...)
```

### Contribution Guide

- [x] I have read and followed the steps listed in the [Contributing Guide](https://github.com/laradumps/laradumps/blob/main/CONTRIBUTING.md).

### Documentation

 This PR requires [Documentation](https://github.com/laradumps/laradumps-docs) update?

- [x] Yes
- [ ] No
- [ ] I have already submitted a Documentation pull request.

### CODE REVIEW

**Comment by luanfreitasdev** [comment]
Hello!, thanks for sending this PR. Could you put more details about it and how to use it?

**Comment by AnandPilania** [comment]
> Can you run` composer fix && composer verify` and fix the problems?

done

**Comment by AnandPilania** [comment]
@luanfreitasdev why not. Will do this today.

**Comment by luanfreitasdev** [comment]
Hello! @AnandPilania . Is there anything pending yet? Maybe I can for the 2x version

**Comment by AnandPilania** [comment]
Bro unable to proceed with the `app`. Lots of error. Tried in Mac & Win. Cn u proceed or fix them?

**Comment by luanfreitasdev** [comment]
It's really hard to send a PR for the app these days. very complex. That's why I'm moving to the 2x version which is being developed in vue

**Comment by AnandPilania** [comment]
closing this in-favour of #68

**Pull request closed without merging**
